### PR TITLE
Added support for resource hierarchy and polymorphism

### PR DESCRIPTION
**Pull request by YegorZuev**

### CODE REVIEW

**Comment by hdpe** [comment]
Thanks very much for your contribution! I'll try to look at it in detail in the next few days.

In the meantime, I notice the CI build has failed because your changes aren't aligned with our code style. You can get IDE code style files from [here](https://github.com/BlackPepperSoftware/bowman/blob/master/development.md). It would be good if you could fix this, and verify the build works with a `mvn install` before updating your PR.

On a change this significant, it would also be good if you could have a think about adding an integration test for this like those in the `bowman-test-it` module.

You can update your PR just by pushing new commits (or force pushing) to the branch in your fork.

Thanks again

**Comment by YegorZuev** [comment]
Hi @hdpe ,
I actually realized that I didn't check integration tests. Could you please provide some instructions on how to run them correctly?

**Comment by YegorZuev** [comment]
Hi @hdpe ,
Do you have any feedback on this PR so far? Do you consider anything is mandatory to add to this changes?

**Comment by hdpe** [comment]
Thanks for pushing back the Checkstyle fixes. Sorry, I haven't had a lot of free time to look at this recently. But thanks a lot for your contribution - I would like to get this functionality incorporated into the project.

For a change like this we will need some tests to define the expected behaviour and ensure it works.

I've had a quick go on an integration test for your changes but I can't get it to work. Please could you have a look?

Once we have some regression tests in place, I'd like us to have a look at refactoring the `RestOperations` code you've added to make it easier to understand, e.g. by extracting the type conversion code and reducing duplication and side-effects.

**Comment by YegorZuev** [comment]
@hdpe , Thank you, I fixed your test with two small fixes.
1. I missed one required change in Client class
2. It seems like it works only when resource url matches class name, which was actually our case, but cannot be a rule, obviously. It works that way because Spring Data Rest sends this type of response:
{
  "_embedded" : {
    "**hierarchyDerivedEntity2s**" : [ {
      "entity2Field" : "y",
      "links" : [ ],
      "_links" : {
        "self" : {
          "href" : "http://localhost:50293/hierarchyDerivedEntity2s/2",
          "title" : null
        },
        "hierarchyDerivedEntity2" : {
          "href" : "http://localhost:50293/hierarchyDerivedEntity2s/2",
          "title" : null
        }
      }
    } ],
    "**hierarchyDerivedEntity1s**" : [ {
      "entity1Field" : "x",
      "links" : [ ],
      "_links" : {
        "self" : {
          "href" : "http://localhost:50293/hierarchyDerivedEntity1s/1",
          "title" : null
        },
        "hierarchyDerivedEntity1" : {
          "href" : "http://localhost:50293/hierarchyDerivedEntity1s/1",
          "title" : null
        }
      }
    } ]
  },

And my implementation of parsing that JSON expects names of that list nodes to match resource url. 
What do you think is a best way to fix that?

**Comment by hdpe** [comment]
So I've had a think about this, and I think that to determine the type of a resource's content you've got two straightforward options:

1. *Determine the type from the resource's self link.* This probably isn't ideal from a REST point of view, as you're then ascribing meaning to URLs rather than rels. However it's probably the best from the point of view of a Bowman user, because all the information necessary to determine a resource's type can then be derived just from the `@RemoteResource` annotations already in place together with the subtype array in your `@Children` annotation or similar.
1. *Determine the type from another of the resource's links.* This is probably better from a REST point of view because you could then additionally use the link's rel to determine the type, rather than just its URL. However this would be annoying for a Bowman user, because you'd then somehow have to map rels to Java types and, as you've seen, the rels generated by Spring Data REST for embedded resources have no semantic meaning, and are in fact ignored by the Spring HATEOAS `Resources` deserializer.

So I think we want to default to 1), but make it possible for people to use 2) if they wish.

In light of this [I've pulled together something](https://github.com/hdpe/bowman/tree/polymorphism-clean) which has adopted some of the spirit of your PR, even if none of the actual code. I'd really appreciate it if you could look it over - preferably check it out and attempt to use it - and see if it solves your use case. I'm not entirely clear what your use case is; for future reference, it would be helpful if you could provide a failing test with any issue (or passing tests with a PR) so we can be clear what problem you're trying to solve.

So my changes:

* Rather than `@Children` I've gone with `@ResourceTypeInfo` with a `subtypes` attribute. I think 'Children' is comparatively a little unclear in its intention, and this new name is analagous to Jackson's `@JsonTypeInfo` with which many users may be familiar.
* I've done away with the `AbstractResource` type you've introduced. Although I can see the benefits of enforcing presence of a `getId` method on all the types, I don't really want to introduce mandatory superclasses for user types as Java's single inheritance makes that unduly restrictive to clients.
* I've introduced a custom Jackson deserializer for Spring HATEOAS's `Resource` type, and all of the type-deriving takes place in here. This keeps it all in one place, prevents the `RestOperations` class ballooning in complexity, and ensures that wherever a `Resource` is obtained by the framework its type has been properly resolved. Your PR seemed to use two different code paths for type resolution depending on whether getResources or getResource was called. I wasn't sure why this was, and figured it would be best to resolve types in the same way in both places. If I've missed something please let me know.
* Rather than grabbing the runtime content type and casting it to a `Class<T>` in various places all through the framework, I've just removed this parameter from methods wherever I can and just retrieved it once in `JavassistClientProxyFactory` at the point the proxy is created. This has actually simplified the code a fair bit and is pretty welcome anyway.
* I've introduced a public interface `TypeResolver` which a user can implement and specify with `@ResourceTypeInfo(typeProvider = ...)` to allow custom type resolution instead of using the default self-link resolution strategy.

And caveats:

* I have omitted the changes your PR also introduced involving using Spring HATEOAS's `PagedResources`. I'm not sure what the intent of these was, but at any rate I don't think they belong in a PR to implement resource hierarchy/polymorphism. It would be great if you could raise a separate issue for your requirements regarding this.
* Just something I noticed: with Spring Data REST at least, ordering is a bit of a funny one. What is the order of a sorted linked collection comprising multiple subtypes? As the subtypes are keyed on their (arbitrary) rels in the response, the order is not really defined. We may have to have a think about how to solve this in the future.

Thanks for your help with this so far and your support of the project.

@datenbrille - interested to know if you have any thoughts on any of this too.

**Comment by datenbrille** [comment]
Give me some more days please. I will take a look.

**Comment by hdpe** [comment]
@datenbrille thanks a lot for your review, it's really appreciated!

I've merged these changes into master. I'm going to wait a bit for some feedback from @YegorZuev before doing a release and closing this PR.

**Comment by hdpe** [comment]
@YegorZuev I'm assuming my commits resolved your issue. Any feedback you have on this at any point, please feel free to add here, and please raise separate issue for paged results if required.

Thanks

**Pull request closed without merging**
