### PR TITLE
Topic add patch support

### PR DESCRIPTION
**Pull request by aelstad**
This adds PATCH support to clients. The PATCH body can be of any type that will produce a set of changes when serialized, for example it is possible to use a Map.

Thank you for a nice library and I hope this (or something similar) is useful upstream as well.

### CODE REVIEW

**Comment by hdpe** [comment]
Hi, thanks very much for your contribution! This is great - it will be good to get some PATCH support. I'm sure this will benefit others.

I've added an integration test demonstrating use of the functionality. Although it's good that you can use Maps, I think you're better off using your own hand-written typed patch objects. This then means you can use the library's current and future features on serialization, such as the linked entity to URI conversion you see here.

A couple of thoughts:

* I'm not sure it's appropriate returning `null` from `patchResource` in the event of the resource not being found. It seems to me that you'd be better off reserving null for when this is returned by the server - i.e., you've somehow managed to update your resource to null. If we get an exception from the client because the server has returned an error like a 404, in this case I think we'd be better off just propagating that or rethrowing it.
* There's an inconsistency now between `patchResource`, which assumes the server returns a representation of the resource, and `putObject` which is void and so makes no such guarantees. I can certainly see how it would be useful to return the representation however, but maybe we need to have two variants of each for the void / `T`-returning case. This point I think we can address as a separate issue (ensure naming and return types of mutating client methods are aligned and support responses containing the resource representation as well as not.)

What do you think?

Thanks again!

**Comment by aelstad** [comment]
Interesting points. My initial idea on 404 was to mimic the behaviour of `get(URI id)`.
After thinking about your feedback I believe the best thing might be to rename to 
`RestOperations.patchResourceForObject` and have it return:
 
 * item on 200 OK. This allows access to the result of the atomic update which querying again 
does not in the case of concurrency.
 * null on 204 No Content. This supports servers that do not return a response body in the case of PATCH.
 * throw/propagate on 404 Not Found. 
 
I think that null responses are probably tied to 204 and not actually updating a resource to be null.
If a server supports literal null resources (unlikely?), a PATCH resulting in a 200 with a literal null
is probably an indication of a problem like a race condition. Using PUT makes much more sense if the update to null is intentional.

In the future I support Clients that can read responses also in the case of PUT. They make sense to me if the server holds state that the client can only read, or if PUT behaves a bit like PATCH in the case of missing fields and multiple clients-versions at the same time. I have noticed that Spring Data REST can return a response for PUT. Spring's `RestTemplate` on the other hand seem to think that a PUT should be a complete overwrite and one has to use `exchange` for such use cases.

However, like you suggest it might make more sense to think about the Client interface as a separate issue and keep the single method named `patch` for now.

**Comment by hdpe** [comment]
Sounds good, I agree with all your reasoning. But in case of the server returning 200 with no content (which may indicate a problem, but also the HTTP and PATCH specs slightly discourage but don't really forbid) I think you'll have to return `null` here too. `RestTemplate` will do this for you. So I don't think there's any benefit in checking for 204s explicitly.

Otherwise great, this sounds good to me. The bit about PUT/PATCH client method names and when invocations should/should not assume returned representations we'll raise in a separate issue. `patchResource` is fine for now. If you could update your PR just removing the 404 swallowing, that would be great. Thanks!

**Comment by aelstad** [comment]
Great. I pushed an update.

**Comment by hdpe** [comment]
merged - thanks very much for your contribution and support of the project!

**Pull request merged**
